/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/markers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMarkers"];
        put?: never;
        post: operations["postMarker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MarkerRequest: {
            /** Format: float */
            latitude?: number;
            /** Format: float */
            longitude?: number;
            name?: string;
        };
        MarkerRequestResponse: {
            response?: string;
        };
        Marker: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: double */
            latitude?: number;
            /** Format: double */
            longitude?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMarkers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Marker"][];
                };
            };
        };
    };
    postMarker: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkerRequest"];
            };
        };
        responses: {
            /** @description Marker added successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MarkerRequestResponse"];
                };
            };
            /** @description Invalid marker location */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MarkerRequestResponse"];
                };
            };
        };
    };
}
